---
version: '3.9'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_TOPIC_REPLICATION_FACTOR=10
      - KAFKA_LOG4J_ROOT_LOGLEVEL=DEBUG

  postgres:
    container_name: {{ cookiecutter.project_slug }}-postgres
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: {{ cookiecutter.project_slug }}
      POSTGRES_USER: {{ cookiecutter.project_slug }}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: ["uvicorn", "--app-dir", "app", "--host", "0.0.0.0", "main:fastapi_app"]
    depends_on:
      - kafka
      - postgres
